on:
  push:
    # paths:
    #   - instana/**.yaml

jobs:
  get-selected-distribution:
    name: Get selected distribution
    runs-on: ubuntu-latest
    outputs:
      DISTRO: ${{ steps.selected-distro.outputs.distro }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get distribution
        id: selected-distro
        run: echo "DISTRO=$(cat selected-distribution)" >> $GITHUB_OUTPUT
  config_validation_job:
    needs: get-selected-distribution
    name: Collector Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Docker container
        run: docker build -t collector-container-${{needs.get-selected-distribution.outputs.DISTRO}} -f Dockerfile --build-arg VERSION=${{needs.get-selected-distribution.outputs.DISTRO}} .
      - name: Run container
        run: docker run collector-container-${{needs.get-selected-distribution.outputs.DISTRO}}


  #     - name: Config validation docker step
  #       id: validation
  #       uses: elizabethshiu/validation-agent@main
